### ISSUE TITLE
ProGuard 7.0.0: obfuscated jar misses file/directory attributes

### ISSUE THREAD

**Issue by OlafRoeder** [Guardsquare/proguard#110]
When generating an obfuscated jar with ProGuard 7.0.0 the jar file has no file attributes like "D" for directory. Therefore the use of MyClass.class.getResource("pathToDirectory") returns null instead of the desired directory. When viewing the jar with 7-Zip it is easy to see, that all file attributes in the whole jar are missing.
Using `-keepdirectories` does not help.

Last worked correctly in ProGuard 6.2.2

I'll provide more information if needed.

**Comment by mrjameshamilton** [comment]
Hi @OlafRoeder, thanks for your report! Do you have have a full sample that reproduces the issue?

**Comment by OlafRoeder** [comment]
@mrjameshamilton Unfortunately none that I'm allowed to publish, I'll try to create one, but it could take some days.

**Comment by IkoRein** [comment]
Hi,

If you access explicitly a file inside .jar directly, the .class.getResource("filename") works, but if you want to get the directory class.getResource("directory"), it fails, i.e. is null in obfuscated .jar.

Simple main for testing:

public class GetResourceIsNullExample {
   public static void main(String[] args) {
            System.out.println("TEST a: " + GetResourceIsNullExample.class.getResource("/css"));
            System.out.println("TEST b: " + GetResourceIsNullExample.class.getResource("/css").toExternalForm());
            System.out.println("TEST c: " + GetResourceIsNullExample.class.getResource("/css/css_file.css"));
            System.out.println("TEST d: " + GetResourceIsNullExample.class.getResource("/css/css_file.css").toExternalForm());
    }
}

I put into the .jar a directory 'css' and inside that a file 'css_file.css'.

If you compile that and run the .jar, it works.
If you then obfuscate the .jar, it fails on the 'TEST b', as the output getResource("/css") is null.

Test: Obfuscated with Proguard 7.0.1 on Windows, run the obfuscated .jar with Java 8 and Java 15.

Cheers.

**Comment by OlafRoeder** [comment]
@mrjameshamilton I managed to create a minimal example which shows the erroneous behaviour, details should all be contained in the example.
https://github.com/OlafRoeder/ProGuardMissingDirectoryAttributes

Happy New Year :)

**Comment by mrjameshamilton** [comment]
Happy new year @OlafRoeder ! Thanks for the sample, that was very useful! Thanks also @IkoRein for the example!

I've confirmed the problem and tracked down the cause to this line: https://github.com/Guardsquare/proguard/blob/master/base/src/proguard/OutputWriter.java#L393

It's caused by a combination of `-keepdirectories` and `-adaptresourcefiles`: if you have `-adaptresourcefiles` the resource writer is wrapped in a `RenamedDataEntryWriter` with a `ResourceFilePoolNameFunction` string transform function - for directories this transform function does not work since they are not in the resource file pool (it always returned null).
