### ISSUE TITLE
Proguard not working with NativeScript 6.5.1

### ISSUE THREAD

**Issue by augustovogt** [Guardsquare/proguard#169]
When configuring Proguard with our application built in NativeScript 6.5.1, it obfuscates the native code of the APK, but when executing it it throws memory corruption. I attach evidence.

Show view Logcat

2021-06-04 13:27:20.734 1279-1279/? W/zygote: Unexpected CPU variant for X86 using defaults: x86
2021-06-04 13:27:20.867 1279-1279/cl.bancoestado.ofuscate.test I/TNS.Runtime: NativeScript Runtime Version 6.5.0, commit 06980ed0e5e2fae2c94a42808e858871cd349c81
2021-06-04 13:27:20.869 1279-1279/cl.bancoestado.ofuscate.test A/libc: Fatal signal 6 (SIGABRT), code -6 in tid 1279 (o.ofuscate.test), pid 1279 (o.ofuscate.test).

Version NativeScript:

MacBook-Pro:AppOfuscate avogt$ tns doctor

✔ Getting environment information 

 

No issues were detected.

✔ Your ANDROID_HOME environment variable is set and points to correct directory.

✔ Your adb from the Android SDK is correctly installed.

✔ The Android SDK is installed.

✔ A compatible Android SDK for compilation is found.

✔ Javac is installed and is configured properly.

✔ The Java Development Kit (JDK) is installed and is configured properly.

✔ Xcode is installed and is configured properly.

✔ xcodeproj is installed and is configured properly.

✔ CocoaPods are installed.

✔ CocoaPods update is not required.

✔ CocoaPods are configured properly.

✔ Your current CocoaPods version is newer than 1.0.0.

✔ Python installed and configured correctly.

✔ The Python 'six' package is found.

✔ Xcode version 12.5.0 satisfies minimum required version 10.

✔ Getting NativeScript components versions information...

⚠ Update available for component nativescript. Your current version is 6.5.1 and the latest available version is 8.0.2.

✔ Component tns-core-modules has 6.5.27 version and is up to date.

⚠ Update available for component tns-android. Your current version is 6.5.0 and the latest available version is 6.5.3.

⚠ Update available for component tns-ios. Your current version is 6.5.0 and the latest available version is 6.5.4.

The evidence corresponds to applying Proguard on a test application in NativeScript 6.5.1

[ProguardConfig.zip](https://github.com/Guardsquare/proguard/files/6600252/ProguardConfig.zip).

Please if you can help me with this error, thank you

**Comment by mrjameshamilton** [comment]
Hi @augustovogt ! 

Can you share a full sample project that reproduces the problem?

Are you using ProGuard or R8? Are you using the latest version of ProGuard? To disable R8 and use the latest ProGuard version, please consult the four steps in the manual here: https://www.guardsquare.com/manual/setup/gradleplugin

**Comment by augustovogt** [comment]
Hi @mrjameshamilton 
    We are using Proguard, I attach files. I hope you can help me with this. Thanks.



[TestProguard.zip](https://github.com/Guardsquare/proguard/files/6602915/TestProguard.zip)

**Comment by mrjameshamilton** [comment]
Hi @augustovogt , as far as I can tell this is not a ProGuard bug but an integration problem. Firstly, the sample is using R8 rather than ProGuard. But the bigger problem is that the configuration file `proguard-rules.pro` is not applied - the path passed to ProGuard is `platforms/android/app/proguard-rules.pro` but *it is not copied* from the `App_Resources/Android/proguard-rules.pro` to the `platforms/android/app/proguard-rules.pro`.

## To use ProGuard, you must disable R8:

* Add the following file to `App_Resources/Android/gradle.properties` (this is automatically picked up by the build):

```
android.enableR8=false
android.enableR8.libraries=false
```

* You should also substitute the dependency for the built-in ProGuard version for the latest version but I don't know how to do this correctly with NativeScript. You can add the following to the `platforms/android/build.gradle` file as below but this change will be lost when you clean and rebuild:

```
buildscript {
    configurations.all {
        resolutionStrategy {
            dependencySubstitution {
                substitute module('net.sf.proguard:proguard-gradle') with module('com.guardsquare:proguard-gradle:7.0.1')
            }
        }
    }
}
```

This substitution is necessary because otherwise you will be using the old ProGuard 6.0.3 that is distributed with Android.

## `proguard-rules.pro`

None of the rules in `proguard-rules.pro` are applied by ProGuard because this file path is wrong. So you should modify the file `App_Resources/Android/app/build.gradle` to use the correct path (using `getAppResourcesPath()`):

```
// Add your native dependencies here:

// Uncomment to add recyclerview-v7 dependency
//dependencies {
//  implementation 'com.android.support:recyclerview-v7:+'
//}

// If you want to add something to be applied before applying plugins' include.gradle files
// e.g. project.ext.googlePlayServicesVersion = "15.0.1"
// create a file named before-plugins.gradle in the current directory and place it there


android {
  defaultConfig {
    minSdkVersion 17
    generatedDensities = []
  }
      buildTypes {
        release {
            // Enables code shrinking, obfuscation, and optimization for only
            // your project's release build type.
            minifyEnabled true

            // Enables resource shrinking, which is performed by the
            // Android Gradle plugin.
            shrinkResources false

            // Includes the default ProGuard rules files that are packaged with
            // the Android Gradle plugin. To learn more, go to the section about
            // R8 configuration files.
            def absolutePathToAppResources = getAppResourcesPath()
            proguardFiles getDefaultProguardFile(
                    'proguard-android-optimize.txt'),
                    "$absolutePathToAppResources/Android/proguard-rules.pro"
        }
    }   

  aaptOptions {
    additionalParameters "--no-version-vectors"
  }
}

```

You also have a typo in `proguard-rules.pro` - one of the `-keep` rules is missing the `-`.

Hopefully this helps! 

The aim of the issue tracker here is to track technical issues and bugs. If you have further usage questions, please head over to the [Guardsquare community](https://community.guardsquare.com/?utm_source=github&utm_medium=site-link&utm_campaign=github-community) where you can get tips and advice on your configuration from our team of engineers and skilled community members.

**Comment by augustovogt** [comment]
Hi @mrjameshamilton,
    Thank you very much for the advice and your help, I will apply the changes indicated, if I have more questions I will let you know through the Guardsquare community.
