### ISSUE TITLE
Annotation in enum constructor leads to bad signature

### ISSUE THREAD

**Issue by AceTheFace** [Guardsquare/proguard#192]
Hi,

since 6.1.0 using an annotation in an enum constructor leads to a bad signature error when accessing the corresponding class file. With 6.0.3 all works fine.
I saw this comment has been added with 6.1.0 which references a JavaC bug regarding the signature attribute: https://github.com/Guardsquare/proguard/blob/proguard6.1.0/core/src/proguard/classfile/attribute/annotation/ParameterAnnotationsAttribute.java#L34

But I wasn't able to figure out what other changes have been applied to ProGuard based on this comment. Is there a setting to restore the old behaviour again? 

Pls let me know if you need more input on this, thanks!

**Comment by mrjameshamilton** [comment]
Hi @AceTheFace ! I've had a look at your sample and it seems to be that the problem is because the order of the `Signature` and `RuntimeVisibleParameterAnnotation` attributes get switched by ProGuard.

Those linked Java compiler bugs may have something to do with it but in this case the `Signature` attribute is actually present in both the original and the processed class file. It seems as though older Java compilers (at least the OpenJDK implementation) may be assuming that the `Signature` attribute appears before the parameter annotations attribute though this is not required by the Java class file specification (https://docs.oracle.com/javase/specs/jvms/se8/html/jvms-4.html#jvms-4.7)

You can see the difference in order in the `javap` dump of the `testEnum/ObfuscatedEnum` constructor here:

```
// Working
  private testEnum.ObfuscatedEnum(java.lang.String);
    descriptor: (Ljava/lang/String;ILjava/lang/String;)V
    flags: ACC_PRIVATE
    Code:
      stack=3, locals=4, args_size=4
         0: aload_0
         1: aload_1
         2: iload_2
         3: invokespecial #10                 // Method java/lang/Enum."<init>":(Ljava/lang/String;I)V
         6: aload_0
         7: aload_3
         8: putfield      #7                  // Field a:Ljava/lang/String;
        11: return
      LineNumberTable:
        line 9: 0
        line 10: 6
        line 11: 11
    Signature: #25                          // (Ljava/lang/String;)V
    RuntimeInvisibleParameterAnnotations:
      0:
        0: #35()
```
```
// Broken
  private testEnum.ObfuscatedEnum(java.lang.String);
    descriptor: (Ljava/lang/String;ILjava/lang/String;)V
    flags: ACC_PRIVATE
    Code:
      stack=3, locals=4, args_size=4
         0: aload_0
         1: aload_1
         2: iload_2
         3: invokespecial #10                 // Method java/lang/Enum."<init>":(Ljava/lang/String;I)V
         6: aload_0
         7: aload_3
         8: putfield      #7                  // Field a:Ljava/lang/String;
        11: return
      LineNumberTable:
        line 9: 0
        line 10: 6
        line 11: 11
    RuntimeInvisibleParameterAnnotations:
      0:
        0: #35()
    Signature: #25                          // (Ljava/lang/String;)V
```

It no longer seems to be an issue with the Java 11 compiler, if you build your sample with a Java 11 compiler it seems to compile fine.

The order is changed by the [ClassElementSorter](https://github.com/Guardsquare/proguard-core/blob/master/src/main/java/proguard/classfile/editor/ClassElementSorter.java) executed by ProGuard from [here](https://github.com/Guardsquare/proguard-core/blob/master/src/main/java/proguard/classfile/editor/ClassElementSorter.java).

There is no configuration workaround but you could [build](https://github.com/Guardsquare/proguard#-building-proguard) a version of ProGuard with that line commented out.

**Comment by mrjameshamilton** [comment]
Hi @andrejusc ! It seems that the sorting of the attributes is not really required and doesn't provide any benefit, in terms of shrinking/optimization. The solution will likely be to [comment out the attribute sorting](https://github.com/Guardsquare/proguard-core/blob/master/src/main/java/proguard/classfile/editor/ClassElementSorter.java#L51) in the same way that the member sorting has already been commented out since ~2006.

Did you confirm in a custom build that it solves your issue? (From [my testing](https://github.com/Guardsquare/proguard/issues/192#issuecomment-1019208602) it seems like it should solve it).

**Comment by andrejusc** [comment]
@mrjameshamilton - well, as other author of this post - I'm getting "bad class" issue here when using obfuscated jar. And I want to avoid spending cycles on custom builds if instead we could come up with some config setting instead to handle such use cases. So if attributes sorting is causing issues from time to time - could we have something like:
```
-keep AttributesUnsorted
```

or similar for some classes?

**Comment by andrejusc** [comment]
Hi @mrjameshamilton - I went now custom build path over current `proguard-core` 9.0.0 master code base and could confirm that commenting attributes sorting as least eliminates Bad class issue for Java 17 in my situation. So if that is not adding any benefits like you said - I suggest then have quick release of 9.0.1 with that commented out for now.

**Comment by andrejusc** [comment]
@mrjameshamilton - will it be you who could cut such 9.0.1 release or should I seek assistance from any member of this project/community? I'd like to avoid using custom build if possible.

**Comment by mrjameshamilton** [comment]
Hi @andrejusc ! We'll try to get a new release out within the next week.

**Comment by andrejusc** [comment]
@mrjameshamilton - any update on planned release 9.0.1?

**Comment by andrejusc** [comment]
@mrjameshamilton - I could see addition of secondary constructor here to ClassElementSorter into 9.0.1:
https://github.com/Guardsquare/proguard-core/pull/34/commits/cb81c3fd505a7c9d931dc1d7f3576654f223fc4a

but how I could use it now via CLI or some config? Do you have an example?

**Comment by mrjameshamilton** [comment]
Hi @andrejusc ! That new version of ProGuardCORE is used by ProGuard 7.2.2 with the attributes sorting as false: https://github.com/Guardsquare/proguard/commit/b3c98ad7290be907575ec66e7e15e76c27964b5a

**Comment by andrejusc** [comment]
@mrjameshamilton - gotcha, sorry I've missed to bump up that dependency as well to 7.2.2. Confirming that all good now with such new combination.
