### ISSUE TITLE
Support Gradle Plugins DSL

### ISSUE THREAD

**Issue by xeruf** [Guardsquare/proguard#225]
https://docs.gradle.org/current/userguide/plugins.html#sec:plugins_block
The `buildscript` block is deprecated, the plugins DSL makes it much easier to apply plugins, would be great if you could support that, too :)
Your setup here does not involve it so far: https://www.guardsquare.com/manual/setup/gradle

**Comment by hakanai** [comment]
Some more unpleasantness. If you're trying to use the form where the version number is specified in `settings.gradle.kts`, like this:

```kotlin
pluginManagement {
    // ...

    resolutionStrategy {
        eachPlugin {
            if (requested.id.id == "com.guardsquare.proguard") {
                useModule("com.guardsquare:proguard-gradle:${requested.version}")
            }
        }
    }

    plugins {
        // ...
        id("com.guardsquare.proguard") version "7.2.2"
    }
}

// build.gradle.kts
plugins {
    id("com.guardsquare.proguard")
}
```

You get an error because `requested.version` is `null` in this situation. So you just have to hardcode the version there instead, I guess.

**Comment by lptr** [comment]
Would it also be possible to publish the plugin to the Gradle plugin portal? https://plugins.gradle.org/

**Comment by ellet0** [comment]
Thank you, the purpose of the `plugins {}` block is to apply plugins with one line without too many configurations or workarounds, for some reason I'm getting this error when applying it in the `plugins {}` block this way:

```console
An exception occurred applying plugin request [id: 'com.guardsquare.proguard', version: '7.4.2', artifact: 'com.guardsquare:proguard-gradle:7.4.2']
> Failed to apply plugin 'com.guardsquare.proguard'.
   > The ProGuard plugin requires the Android plugin to function properly.
     For Java projects, you can manually declare a ProGuardTask instead of applying the plugin:
```

**Comment by mts2200** [comment]
Same issue

**Comment by mrjameshamilton** [comment]
The ProGuard Gradle plugin only supported Android and does not support Java / Kotlin projects. There is a separate issue to track support for a plugin for Java projects (#107).

The way to apply ProGuard in a non-Android Gradle project is to create a task of type `ProGuardTask` rather than applying the plugin, as described in the [manual](https://www.guardsquare.com/manual/setup/gradle) and [examples](https://github.com/Guardsquare/proguard/blob/master/examples/application/build.gradle#L42).

Since [no further support is planned for Android projects](https://github.com/Guardsquare/proguard/issues/280#issuecomment-1798563020), I will close this issue as it's not relevant for Java projects without having plugin support (#107).
