### ISSUE TITLE
java.lang.VerifyError: Constructor must call super() or this() before return

### ISSUE THREAD

**Issue by Coderx64** [Guardsquare/proguard#24]
Hi, after processing this code with proguard version starts with 6.0+(5.3.3 works fine) i got this exception.

```
java.lang.VerifyError: Constructor must call super() or this() before return
Exception Details:
  Location:
    com/example/TestSingletone.<init>()V @0: return
  Reason:
    Error exists in the bytecode
  Bytecode:
    0x0000000: b1
```

example
```
public class TestSingletone {

    private static TestSingletone singletone;

    public static synchronized TestSingletone getInstance() {
        if (singletone == null) {
            singletone = new TestSingletone();
        }

        return singletone;
    }

    private TestSingletone() {

    }

}
```

after call `TestSingletone.getInstance()` i've got a VerifyError.

my proguard config
```
-target 1.8

-keep public class com.example.TestSingletone {
    public <fields>;
    protected <fields>;
    public <methods>;
}

-assumenosideeffects public class java.lang.String {
    public <init>();
}
```

java version is 
```
openjdk version "1.8.0_232"
OpenJDK Runtime Environment (Zulu 8.42.0.23-CA-win64) (build 1.8.0_232-b18)
OpenJDK 64-Bit Server VM (Zulu 8.42.0.23-CA-win64) (build 25.232-b18, mixed mode)
```

javac version is 
`javac 1.8.0_232`

Could you please look to this?

**Comment by TimvdBroecke** [comment]
Thank you for the clear report and sample.

The problem comes from this rule:
```
-assumenosideeffects public class java.lang.String {
    public <init>();
}
```

ProGuard recursively marks the specified member in the hierarchy of the specified class. Because all classes extend java.lang.Object, any -assumenosideeffects rule that specifies the member `<init>();` causes the parameterless constructor of java.lang.Object to be marked as having no side effects, which is certainly incorrect.

The result here is that during the **code/removal/advanced** optimization step ProGuard removes the invocation of java.lang.Object.<init> from the "empty" constructor of TestSingletone (the generated bytecode still calls `Object.<init>()`). The Verifier notices that the resulting constructor is invalid and crashes the program as expected.

**Comment by Coderx64** [comment]
Thank you for the response. I will remove any `<init>();` members from my pg config.
