### ISSUE TITLE
Readd -target option for Java 12+

### ISSUE THREAD

**Issue by Akaguiri** [Guardsquare/proguard#243]
Hello,

I'm using Proguard for optimizing my application and I need to switch between legacy Java 8 and new Java 17. I have a Ant task to do that and I'm using <proguard target="1.8|17" shrink="true" ...> ... a lot of stuff ... </proguard> to build and optimize

With Java 8 I have no issue but with Java 17 I have this error:
**build.xml:xxx: -target can only be used with class file versions <= 55 (Java 11).
The input classes contain version 61 class files which cannot be backported to target version (61).**

I have read in release notes of 7.2.1 changes about -target depreciation but this is really complicated without that, the only solution I see would be to duplicate my whole <proguard/> tag and add a if:true/if:false condition to execute one with target and the other without.

Or maybe there is a better solution ?

PS: I'm using Proguard 7.2.1, no issue with Proguard 7.2.0.

Regards,

**Comment by mrjameshamilton** [comment]
Hi @Akaguiri !

Can you clarify your use-case? It seems like you have a mix of Java 8 and Java 17 classes and your target is Java 8? If you don't need to change the versions, then you don't need to use `-target`.

The reason that we marked this as deprecated is because the backporter only ever supported maximum Java 11 features. The changing of the target version requires also backporting new Java / bytecode features to code that is supported by older versions. Since there has been no updates to the backporter after Java 11, backporting Java 11+ classes can result in invalid classes e.g. if you backport records or your code uses some JDK library calls that are only available for Java 11 these need to been backported.

Since there are no plans to backport new features and Java is now on a 6 monthly release cycle, it seemed safer to disable the backporting of newer class versions to older versions; since otherwise it can result in classes that don't work on the specified target version.

**Comment by Akaguiri** [comment]
Hi,

I have only one ANT build script for every releases (Java 8 and Java 17), I have a configuration script to define some properties like the targeted Java version (<property name="target" value="1.8"/>) and I use it for javac and my Proguard task (<proguard target ="${target}" ...> ... 50 lines of config ... </proguard>. I don't plan to backport anything, if you see my error message I have a class file v61 "backported" to v61 when I use Java 17.

Initially I did planed to migrate to Java 17 but Eclipse decided something else; ANT tasks requires Java 11+ for running in latest version (2022-03) so I need to use Java 17 inside Eclipse but with a backward compatibility to Java 8 for now (XP support for our application). The other possibility would be to stuck to an older Eclipse version but 2020-XX series was pretty bugged and auto-update, even if it can be disabled is a problem.

Maybe option should be still here but forbid backporting when this is not possible), but if class version remains identical of compatible it should work without issue. What do you think ?
