### ISSUE TITLE
Support for AGP 8+

### ISSUE THREAD

**Issue by romtsn** [Guardsquare/proguard#280]
We're running tests for our Gradle plugin against AGP/Gradle matrix, and as part of that we've recently started to run our tests on AGP 8.0.0-alpha01. Unfortunately, proguard does not support this version yet, because the Transform API has been [removed](https://developer.android.com/studio/releases/gradle-plugin-api-updates#transform-removed).

Are there any plans to support it anytime soon? AGP 8 is gonna become stable most likely by the end of the year, so that'd be great to have it supported. 

Here's the exact error I got in my Gradle logs:

```
* What went wrong:
A problem occurred evaluating project ':examples:android-guardsquare-proguard'.
> Failed to apply plugin 'com.guardsquare.proguard'.
   > API 'android.registerTransform' is removed.
     
     For more information, see https://developer.android.com/studio/releases/gradle-plugin-api-updates#transform-api.
     To determine what is calling android.registerTransform, use -Pandroid.debug.obsoleteApi=true on the command line to display more information.
```

**Comment by gsprdev** [comment]
This remains an issue today, with the latest versions.
The following two dependencies are incompatible, with the same error as above:

```kotlin
buildscript {
    dependencies {
        classpath("com.android.tools.build:gradle:8.0.0-rc01")
        classpath("com.guardsquare:proguard-gradle:7.3.2")
    }
}
```

**Comment by chrisjenx** [comment]
This is a P0 as this is completely broken now and stopping people upgrading

**Comment by jvdestefano** [comment]
Understood. We are currently evaluating the roadmap for ProGuard inclusive of AGP 8 support, and we will be able to provide more clarity in the coming weeks.

**Comment by jvdestefano** [comment]
There has been no further development nor is it planned at this time.

**Comment by listvin** [comment]
[As far as I can see](https://developer.android.com/build/releases/gradle-plugin#expandable-2), targeting Android API 34 requires AGP 8.1.1+
So there is currently no way of using Proguard with new Android apps?
Kinda bummer =/
Is this still not planned?

**Comment by mrjameshamilton** [comment]
Since [R8](https://developer.android.com/build/shrink-code) is now the default Android shrinker, there is little need or demand for using ProGuard on Android apps. For this reason, we don't have any current plans for further support for AGP.

If there is a need or a use-case, one route for the community to take would be for AGP support to be implemented in a manner similar to the ProGuard Maven plugin (https://github.com/wvengen/proguard-maven-plugin): as a separate project that implements a ProGuard AGP plugin calling out to ProGuard.

R8 is compatible with ProGuard keep rules, so [the manual](https://www.guardsquare.com/manual/configuration/usage) and tools like the [ProGuard Playground](https://playground.proguard.com/) can be used with R8 configurations.

**Comment by peterdk** [comment]
I tested with latest R8, but it lacks in terms of optimization. My app (a piano app) has noticeable more latency, even though everything is profiled and optimized. So I do have a need for proguard in AGP 8+. Since you also make Dexguard (or does that not exist anymore), I would assume it's not that much work to also add proguard support? I am willing to invest in this, since the app makes a relevant amount of revenue. I'll send a email to discuss further.

**Comment by ellet0** [comment]
> Since [R8](https://developer.android.com/build/shrink-code) is now the default Android shrinker, there is little need or demand for using ProGuard on Android apps. For this reason, we don't have any current plans for further support for AGP.
> 

**Not directly related**
 
![image](https://github.com/Guardsquare/proguard/assets/73608287/2971ace1-624e-43e3-9369-a5a7a829fe8c)

Proguard still includes some things related to Android and R8 in the JAR

![image](https://github.com/Guardsquare/proguard/assets/73608287/9b6c3ee4-2039-4fc6-8c70-c905e26b7276)

While it's not an issue, and in most cases, it's just naming, separating Android-specific components from Kotlin/JVM and regular JVM Java projects would help in maintaining clarity and avoid any potential confusion. This separation could enhance the focus and efficiency for developers who are working exclusively on non-Android projects.
