### ISSUE TITLE
JDK 20 support

### ISSUE THREAD

**Issue by dougxc** [Guardsquare/proguard#294]
JDK 20 is going to land in [March 2023](https://mail.openjdk.org/pipermail/jdk-dev/2022-October/007108.html). It would be great to have JDK 20 support in ProGuard soon to be prepared.

**Comment by dougxc** [comment]
Hi @mrjameshamilton , is there a rough ETA as to when there will be a release with support for JDK 20?

**Comment by mrjameshamilton** [comment]
Hi @dougxc ! Since there doesn't seem to be any relevant changes required apart from the version bump; I've bumped the max supported version in ProGuardCORE.

To already test it you could build ProGuardCORE + ProGuard yourself:

* Publish ProGuardCORE to mavenLocal: `./gradlew publishToMavenLocal`
* Update the ProGuardCORE version in the ProGuard `gradle.properties` file
* Build ProGuard: `./gradlew assemble`

I also attach a pre-built zip distribution: [proguard-7.3.2.zip](https://github.com/Guardsquare/proguard/files/10533606/proguard-7.3.2.zip)

**Comment by dougxc** [comment]
I've run our tests with that pre-built zip and everything works - thanks! Hopefully this means a release with these changes can be made soon.

**Comment by dougxc** [comment]
@mrjameshamilton is there any chance a release could be made soon?

**Comment by mrjameshamilton** [comment]
Hi @dougxc ! I'll try to make a release next week.

**Comment by dougxc** [comment]
Hi @mrjameshamilton we seem to be hitting non-determ

**Comment by dougxc** [comment]
Sorry - accidental press of the wrong button!

**Comment by mrjameshamilton** [comment]
Released in 7.3.2 https://github.com/Guardsquare/proguard/releases/tag/v7.3.2
