### ISSUE TITLE
Keep kotlin metadata only for specified classes

### ISSUE THREAD

**Issue by AntonShuvaev** [Guardsquare/proguard#296]
If you add `-keep class kotlin.Metadata`, the metadata is preserved for all classes. This exposes the internal information of the classes and makes obfuscation less useful. I would like to have option to keep metadata only for certain classes, kind of `-keepkotlinmetadata class MyClass`

**Comment by mrjameshamilton** [comment]
Hi @AntonShuvaev !

By default, ProGuard simply treats the Kotlin metadata annotation like any other Java annotation: if the Kotlin metadata annotation is not used at all, and there is no keep rule for it then ProGuard will remove it since it's unused.

Since version 7.0, ProGuard has had the ability to process Kotlin metadata but only when `-keepkotlinmetadata` is supplied in the configuration. If `-keepkotlinmetadata` was not provided then the metadata would be kept if there is a `-keep class kotlin.Metadata` keep rule but the metadata would not be in-sync with the obfuscated names nor shrunk.

Since version 7.3.0, ProGuard enables Kotlin metadata processing when a keep rule for the Kotlin metadata annotation is detected (i.e. `-keep class kotlin.Metadata`). One reason for this is that some libraries (such as Kotlin reflection) require the metadata and will provide this rule as a consumer rule or require this rule to be added to the configuration. If ProGuard does not process the metadata then the metadata is neither adapted with obfuscated names nor shrunk, so ProGuard now enables processing if this rule is detected.

When processing Kotlin metadata, ProGuard 7.+ does not preserve metadata for all classes. When using `-keep class kotlin.Metadata` (previously `-keepkotlinmetadata`), ProGuard does the following:

* Forcibly removes Kotlin metadata where it's not specifically kept by a keep rule (see [KotlinAnnotationStripper](https://github.com/Guardsquare/proguard/blob/c4a5a891948deb51e62a6f22c53e5a19d0975b82/base/src/main/java/proguard/strip/KotlinAnnotationStripper.java#L38))
```
Removing @kotlin.Metadata annotation where not kept...
  Original number of classes with @kotlin.Metadata:            860
  Final number of classes with @kotlin.Metadata:               242
```
* Synchronise names in the metadata so that they match the obfuscated Java names, for example if a Java method is renamed the Kotlin counterpart metadata will also be renamed
* Shrink the contents of metadata, for example if a Java method is unused the Kotlin counterpart metadata will also be removed
```
Adapting Kotlin metadata...
  Number of Kotlin classes adapted:              3
```
