### ISSUE TITLE
Strings become unremovable. (proguard5.3.2 to proguard6.1.1)

### ISSUE THREAD

**Issue by Klayflash** [Guardsquare/proguard#4]
I want to remove string "resistant_string" from HelloWorld.java (see example).
proguard5.3.2 does it fine but proguard6.1.1 does not.
[javaSandbox.zip](https://github.com/Guardsquare/proguard/files/3472748/javaSandbox.zip)

Which options should I use to keep the string removed?

**Comment by netomi** [comment]
This seems to be due to a refactoring of the way advanced code removal works.

The InstructionUsageMarker$MyInitialUsageMarker visits PUTFIELD instructions and marks reverse dependencies. While doing so it does not take into account if the instruction has side effects and will in any case mark the instruction itself (even if the field is write-only):

see https://github.com/Guardsquare/proguard/blob/master/core/src/proguard/optimize/evaluation/InstructionUsageMarker.java#L708

If this call is modified to take into account if the current instruction has side effects, and only mark it in this case, the sample run the same as in previous versions of ProGuard.

DexGuard is also affected by this problem.

**Comment by netomi** [comment]
Proguard 6.2.0 has been released including a fix for this issue.
