### ISSUE TITLE
[7.0.0] Unnecessary dependency on com.android.tools.build

### ISSUE THREAD

**Issue by boris-petrov** [Guardsquare/proguard#44]
Thank you for releasing ProGuard 7 with Java 14 support!

One thing which I find strange (and perhaps can be improved on ProGuard's side) is the dependency on `com.android.tools.build:gradle:3.0.0`. Just updating ProGuard's version to 7.0.0 (and changing the artifact ID) leads to a `Could not find com.android.tools.build:gradle:3.0.0.` error. I had to add `google()` as a repository for my build script to resolve that.

I'm developing a Java server application which has absolutely nothing to do with Android so a dependency on something with `android` in the name seems unneeded.

**Comment by EricSalemi** [comment]
The artifact ID should not have not changed.
Only the group ID changed from `net.sf.proguard` to `com.guardsquare`.

I assume you depend on `com.guardsquare:proguard-gradle:7.0.0` which is as far as I can tell the only artifact pulling a dependency on `com.android.tools.build:gradle:3.0.0`. Is this correct?

Note that previous stable version of proguard ([6.2.2](https://mvnrepository.com/artifact/net.sf.proguard/proguard-gradle/6.2.2)) has the same depedency towards `com.android.tools.build:gradle:3.0.0`. Which version of proguard are you upgrading from?

**Comment by boris-petrov** [comment]
@EricSalemi - thanks for the support!

Indeed, only the group ID has changed, sorry for the confusion. I updated from `net.sf.proguard:proguard-gradle:6.2.2` to `com.guardsquare:proguard-gradle:7.0.0`. As I said, doing nothing more lead to a missing module exception (I didn't depend on `google()`). After adding it, the error went away. The full build script is:

```gradle
buildscript {
	repositories {
		mavenCentral()
		jcenter()
		google() // without this, 7.0.0 blows up. 6.2.2 didn't.
	}

	dependencies {
		classpath 'com.guardsquare:proguard-gradle:7.0.0'
	}
}
```

**Comment by EricSalemi** [comment]
The dependency towards `com.android.tools.build:gradle` has always been present in the code of ProGuard and is necessary for integration with the Android Gradle Plugin from Google. We understand that you use only a part of the `proguard-gradle` component, namely the ProGuard Gradle task, but it is currently bundled together with the ProGuard Gradle plugin, which effectively depends on `com.android.tools.build:gradle`.

The difference in behavior you see between `6.2.2` and `7.0.0` is due to the dependency scope which went from `provided` to `compile` in the published POM file. The situation is not ideal for you but corresponds more accurately now to the actual dependencies of the package.

Declaring the `google()` repository is an effective work around.

Feel free to file a new issue if you feel the task and plugin should be packaged separately.
